version: '3.9'
services:
  naver-land-crawler:
    container_name: naver-land-crawler
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - naver-land-crawler-network
    depends_on:
      - mysql
      - redis
  mysql:
    container_name: mysql
    image: mysql:8.4.1
    command:
      - --mysql_native_password
    environment:
      MYSQL_DATABASE: 'localhost'
      MYSQL_ROOT_PASSWORD: '!@#localhost'
      MYSQL_USER: 'crawler'
      MYSQL_PASSWORD: '!@#crawler'
      LANG: ko_KR.UTF-8
      LANGUAGE: ko_KR:ko
      LC_ALL: ko_KR.UTF-8
    volumes:
      - ./docker/mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    networks:
      - naver-land-crawler-network
  redis:
    container_name: redis
    image: redis:7.2.5
    ports:
      - '6379:6379'
    networks:
      - naver-land-crawler-network
networks:
  naver-land-crawler-network:
    driver: bridge